
services:
  php:
    image: ghcr.io/eventpoints/php:main
    platform: linux/amd64
    volumes:
      - .:/app:cached
      - php_socket:/var/run/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: php
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql/data:rw

volumes:
  php_socket:
